/**
 * Drizzle-free contracts for backend and query-strategy authors.
 *
 * Applications normally use `Store` factories from the package root. This
 * entrypoint names every input and output needed to implement a custom
 * `GraphBackend`, `AdapterBackend`, `FulltextStrategy`, or `VectorStrategy`
 * without importing an execution adapter.
 */
export type {
  ResolvedSqlTableNames,
  SqlTableNames,
} from "../query/compiler/schema";
export type { FulltextStrategy } from "../query/dialect/fulltext-strategy";
export {
  ALL_FULLTEXT_MODES,
  buildFulltextCapabilities,
  fts5Strategy,
  tsvectorStrategy,
} from "../query/dialect/fulltext-strategy";
export type {
  DialectAdapter,
  DialectCapabilities,
  DialectRecursiveQueryStrategy,
  DialectStandardQueryStrategy,
  DialectVectorPredicateStrategy,
  SqlDialect,
} from "../query/dialect/types";
export type {
  VectorSlot,
  VectorStrategy,
} from "../query/dialect/vector-strategy";
export {
  assertFiniteEmbedding,
  assertVectorMinScore,
  assertVectorSearchLimit,
  buildVectorCapabilities,
  quoteIdentifier,
  shortHash,
  VECTOR_CONTRIBUTION_PREFIX,
  vectorMinScoreCondition,
  vectorPhysicalName,
  vectorScoreExpression,
} from "../query/dialect/vector-strategy";
export type {
  RenderedSql,
  SqlChunk,
  SqlFragment,
  SqlIdentifierChunk,
  SqlParameterChunk,
  SqlPlaceholderChunk,
  SqlTag,
  SqlTextChunk,
} from "../query/sql-fragment";
export {
  isSqlFragment,
  isSqlPlaceholder,
  Placeholder,
  renderPostgres,
  renderSql,
  renderSqlInline,
  renderSqlite,
  sql,
} from "../query/sql-fragment";
export type {
  CompiledRowsSql,
  CompiledSelectSql,
  CompiledStatementSql,
  CompiledTemporaryStatementSql,
  IntentSql,
  SqlIntent,
} from "../query/sql-intent";
export type {
  StrategyTableContribution,
  TableContribution,
} from "./table-contribution";
export {
  BASE_CONTRIBUTION_OWNER,
  FULLTEXT_CONTRIBUTION_NAME,
} from "./table-contribution";
export type {
  AdapterBackend,
  AdapterBackendTransactions,
  BackendCapabilities,
  BackendIdentity,
  BackendLifecycle,
  BackendMaintenance,
  BackendTransactions,
  CheckUniqueBatchParams,
  CheckUniqueParams,
  ClaimIndexMaterializationParams,
  CommitSchemaVersionExpected,
  CommitSchemaVersionParams,
  ContributionMaterializationBackend,
  ContributionMaterializationIdentity,
  ContributionMaterializationRow,
  CountEdgesByKindParams,
  CountEdgesFromParams,
  CountNodesByKindParams,
  CreateVectorIndexParams,
  DeleteEdgeParams,
  DeleteEdgesBatchParams,
  DeleteEmbeddingParams,
  DeleteFulltextBatchParams,
  DeleteFulltextParams,
  DeleteNodeParams,
  DeleteUniqueParams,
  DropVectorIndexParams,
  EdgeEntityReadBackend,
  EdgeEntityWriteBackend,
  EdgeExistsBetweenParams,
  EdgeRow,
  FilteredApproximateSearch,
  FilteredApproximateSearchMode,
  FindEdgesByKindParams,
  FindEdgesConnectedToParams,
  FindNodesByKindParams,
  FulltextBatchRow,
  FulltextCapabilities,
  FulltextOperationBackend,
  FulltextQueryMode,
  FulltextSearchParams,
  FulltextSearchResult,
  GraphAnalyticsCapabilities,
  GraphBackend,
  GraphEntityReadBackend,
  GraphEntityWriteBackend,
  GraphLifecycleBackend,
  GraphReadBackend,
  HardDeleteEdgeParams,
  HardDeleteNodeParams,
  HybridSearchParams,
  HybridSearchRow,
  IndexMaterializationBackend,
  IndexMaterializationRow,
  InsertEdgeParams,
  InsertNodeParams,
  InsertSchemaParams,
  InsertUniqueParams,
  KindRemovalRow,
  LiveNodeRow,
  NodeEntityReadBackend,
  NodeEntityWriteBackend,
  NodeRow,
  QueryExecutionBackend,
  RawQueryExecutionBackend,
  RawStatementExecutionBackend,
  RecordContributionMaterializationParams,
  RecordIndexMaterializationParams,
  RecordKindRemovalParams,
  ReleaseIndexMaterializationClaimParams,
  RemovalMaterializationBackend,
  RowProps,
  SchemaCommitBackend,
  SchemaReadBackend,
  SchemaVersionRow,
  SetActiveVersionParams,
  SqlCompilationBackend,
  TombstonedNodeRow,
  TransactionBackend,
  TransactionOptions,
  TransactionReadBackend,
  TrustedImportSession,
  UniqueConstraintBackend,
  UniqueRow,
  UpdateEdgeParams,
  UpdateNodeParams,
  UpsertEmbeddingBatchParams,
  UpsertEmbeddingBatchRow,
  UpsertEmbeddingParams,
  UpsertFulltextBatchParams,
  UpsertFulltextParams,
  VectorCapabilities,
  VectorIndexType,
  VectorMetric,
  VectorOperationBackend,
  VectorSearchParams,
  VectorSearchResult,
} from "./types";
export {
  D1_MAX_BIND_PARAMETERS,
  DURABLE_OBJECT_MAX_BIND_PARAMETERS,
  isLiveNodeRow,
  isTombstonedNodeRow,
  MODERN_SQLITE_MAX_BIND_PARAMETERS,
  normalizeGraphAnalyticsCapabilities,
  POSTGRES_CAPABILITIES,
  POSTGRES_MAX_BIND_PARAMETERS,
  rowPropsToJsonText,
  rowPropsToObject,
  SQLITE_CAPABILITIES,
  SQLITE_MAX_BIND_PARAMETERS,
} from "./types";

// Supporting vocabulary referenced by the authoring contracts above. Keeping
// it nameable from this entrypoint makes API Extractor's forgotten-export
// diagnostic a zero-tolerance gate for future backend contract additions.
export type {
  Cardinality,
  Collation,
  DeleteBehavior,
  EndpointExistence,
  IndexEntity,
  JsonValue,
  KindAnnotations,
  KindEntity,
  NullCheckOp,
  TemporalMode,
  UniquenessScope,
} from "../core/types";
export type {
  ExtensionArrayItemType,
  ExtensionArrayProperty,
  ExtensionBooleanProperty,
  ExtensionEdgeDef,
  ExtensionEdgeIndex,
  ExtensionEmbeddingModifier,
  ExtensionEnumProperty,
  ExtensionIndex,
  ExtensionIndexWhere,
  ExtensionNodeDef,
  ExtensionNodeIndex,
  ExtensionNumberProperty,
  ExtensionObjectFieldProperty,
  ExtensionObjectProperty,
  ExtensionOntologyRelation,
  ExtensionPropertyModifiers,
  ExtensionPropertyType,
  ExtensionSearchableModifier,
  ExtensionStringProperty,
  ExtensionUniqueConstraint,
  ExtensionUniqueWhere,
  GraphExtension,
  GraphExtensionVersion,
} from "../graph-extension/extension-types";
export type {
  EdgeIndexDeclaration,
  EdgeIndexDirection,
  IndexDeclaration,
  IndexDeclarationBase,
  IndexOrigin,
  IndexScope,
  IndexWhereExpression,
  IndexWhereLiteral,
  IndexWhereOp,
  IndexWhereOperand,
  NodeIndexDeclaration,
  RelationalIndexDeclaration,
  RelationalIndexMethod,
  SystemColumnName,
  VectorIndexDeclaration,
  VectorIndexImplementation,
  VectorIndexMetric,
  VectorIndexParams,
} from "../indexes/types";
export type { MetaEdgeName } from "../ontology/constants";
export { ALL_META_EDGE_NAMES } from "../ontology/constants";
export type { InferenceType } from "../ontology/types";
export type { ValueType } from "../query/ast";
export type { JsonPointer } from "../query/json-pointer";
export type {
  JsonSchema,
  SerializedClosures,
  SerializedEdgeDef,
  SerializedMetaEdge,
  SerializedNodeDef,
  SerializedOntology,
  SerializedOntologyRelation,
  SerializedSchema,
  SerializedUniqueConstraint,
} from "../schema/types";
