/**
 * Drizzle-free contracts for backend and query-strategy authors.
 *
 * Applications normally use `Store` factories from the package root. This
 * entrypoint names every input and output needed to implement a custom
 * `GraphBackend`, `AdapterBackend`, `FulltextStrategy`, or `VectorStrategy`
 * without importing an execution adapter.
 */
export type {
  ResolvedSqlTableNames,
  SqlTableNames,
} from "../query/compiler/schema";
export type { FulltextStrategy } from "../query/dialect/fulltext-strategy";
export {
  ALL_FULLTEXT_MODES,
  buildFulltextCapabilities,
  fts5Strategy,
  tsvectorStrategy,
} from "../query/dialect/fulltext-strategy";
export type {
  DialectAdapter,
  DialectCapabilities,
  DialectRecursiveQueryStrategy,
  DialectStandardQueryStrategy,
  DialectVectorPredicateStrategy,
  InListParameterOptions,
  SqlDialect,
} from "../query/dialect/types";
export type {
  VectorSlot,
  VectorStrategy,
} from "../query/dialect/vector-strategy";
export {
  assertFiniteEmbedding,
  assertVectorMinScore,
  assertVectorSearchLimit,
  buildVectorCapabilities,
  quoteIdentifier,
  shortHash,
  VECTOR_CONTRIBUTION_PREFIX,
  vectorMinScoreCondition,
  vectorPhysicalName,
  vectorScoreExpression,
} from "../query/dialect/vector-strategy";
export type {
  RenderedSql,
  SqlChunk,
  SqlFragment,
  SqlIdentifierChunk,
  SqlParameterChunk,
  SqlPlaceholderChunk,
  SqlTag,
  SqlTextChunk,
} from "../query/sql-fragment";
export {
  isSqlFragment,
  isSqlPlaceholder,
  Placeholder,
  renderPostgres,
  renderSql,
  renderSqlInline,
  renderSqlite,
  sql,
} from "../query/sql-fragment";
export type {
  CompiledRowsSql,
  CompiledSelectSql,
  CompiledStatementSql,
  CompiledTemporaryStatementSql,
  IntentSql,
  SqlIntent,
} from "../query/sql-intent";
export { resolveStampedValidityLowerBound } from "../utils/date";
export {
  BATCH_POINT_READ,
  batchPointReadMembers,
  batchPointReadVerdict,
  bindCore,
  bindExtra,
  bindExtraIfReachable,
  type BundleBinding,
  type BundleVerdictOf,
  CAPABILITY_BUNDLES,
  type CapabilityBundleDefinition,
  type CapabilityBundleDisposition,
  type CapabilityBundleExtra,
  type CapabilityBundleId,
  type CapabilityBundleOperation,
  type CapabilityBundleOperationSite,
  type CapabilityCrossCheck,
  type CapabilityExtraSpec,
  CLAIMS,
  claimsMembers,
  claimsVerdict,
  type ClaimsVerdictThunk,
  CONTRIBUTION_HEALTH,
  contributionHealthMembers,
  contributionHealthVerdict,
  createClaimsVerdictThunk,
  type DeferredUnbundledMember,
  type ExtraMember,
  type ExtrasOf,
  type ExtraVerdict,
  type ExtraVerdicts,
  type GatedBundleDefinition,
  type GatedBundleVerdict,
  type GraduatedBundleDefinition,
  type GraduatedBundleVerdict,
  missingRequiredExtras,
  type OperationNames,
  type OptionalGraphBackendMember,
  type OptionalKeys,
  type PartialBundleBinding,
  type ReasonedUnbundledMember,
  RECORDED_REVISION_ORIGINS,
  recordedRevisionOriginsMembers,
  recordedRevisionOriginsVerdict,
  type RequiredExtrasOf,
  requireExtras,
  requireWriteFence,
  resolveBundle,
  resolveWriteFencePlan,
  type SpecOf,
  STATEMENT_EXECUTION,
  statementExecutionMembers,
  statementExecutionVerdict,
  UNBUNDLED_OPTIONAL_MEMBERS,
  type UnbundledOptionalMember,
  UNIQUE_SIDECAR_BATCH,
  uniqueSidecarBatchMembers,
  uniqueSidecarBatchVerdict,
  type WriteFencePlan,
  WS5B_SEED_BUNDLES,
  type Ws5bBundleId,
} from "./capabilities";
export type { RecursiveTraversalVerdict } from "./capabilities/recursive-traversal";
export {
  assertRecursiveTraversal,
  assumeRecursiveTraversalSupported,
  recursiveTraversalUnsupportedError,
  resolveRecursiveTraversal,
} from "./capabilities/recursive-traversal";
export {
  deleteLegacyRecordedAnchorMap,
  type DeleteLegacyRecordedAnchorMapOptions,
  migrateLegacyRecordedTime,
  type MigrateLegacyRecordedTimeOptions,
  type MigrateLegacyRecordedTimeResult,
  migrateRecordedAnchor,
  type MigrateRecordedAnchorOptions,
} from "./migrate-recorded-time";
export {
  repairInvertedValidityWindows,
  type RepairInvertedWindowsOptions,
  type RepairInvertedWindowsReport,
  type RepairRelation,
  type RepairRelationScope,
} from "./repair-validity-windows";
export type {
  StrategyTableContribution,
  TableContribution,
} from "./table-contribution";
export {
  BASE_CONTRIBUTION_OWNER,
  FULLTEXT_CONTRIBUTION_NAME,
} from "./table-contribution";
export type {
  AdapterBackend,
  AdapterBackendTransactions,
  BackendCapabilities,
  BackendIdentity,
  BackendLifecycle,
  BackendMaintenance,
  BackendTransactions,
  CheckUniqueBatchParams,
  CheckUniqueParams,
  ClaimEdgeCardinalityParams,
  ClaimIndexMaterializationParams,
  CommitSchemaVersionExpected,
  CommitSchemaVersionIfKindsEmptyResult,
  CommitSchemaVersionParams,
  ConstraintFenceViolationRows,
  ContendedEdgeRow,
  ContendedUniqueRow,
  ContributionCapabilities,
  ContributionDiagnostic,
  ContributionDiagnosticState,
  ContributionMaterializationBackend,
  ContributionMaterializationIdentity,
  ContributionMaterializationRow,
  ContributionProbeContribution,
  ContributionProbeEntry,
  ContributionProbeResult,
  ContributionProbeState,
  ContributionRebuildResult,
  ContributionRebuildScope,
  ContributionRepairEntry,
  ContributionRepairResult,
  ContributionRepopulationStats,
  CountEdgesByKindParams,
  CountEdgesFromParams,
  CountNodesByKindParams,
  CreateVectorIndexParams,
  DatabaseExtensionName,
  DeleteEdgeParams,
  DeleteEdgesBatchParams,
  DeleteEmbeddingParams,
  DeleteFulltextBatchParams,
  DeleteFulltextParams,
  DeleteNodeParams,
  DeleteUniqueParams,
  DisjointOverlapRow,
  DropVectorIndexParams,
  EdgeCardinalityDeclaration,
  EdgeClaimOutcome,
  EdgeEntityReadBackend,
  EdgeEntityWriteBackend,
  EdgeExistsBetweenParams,
  EdgeRow,
  FilteredApproximateSearch,
  FilteredApproximateSearchMode,
  FindEdgesByEndpointSetParams,
  FindEdgesByHeterogeneousEndpointSetParams,
  FindEdgesByKindParams,
  FindEdgesConnectedToParams,
  FindNodesByKindParams,
  FulltextBatchRow,
  FulltextCapabilities,
  FulltextOperationBackend,
  FulltextQueryMode,
  FulltextSearchParams,
  FulltextSearchResult,
  GraphAnalyticsCapabilities,
  GraphBackend,
  GraphEntityReadBackend,
  GraphEntityWriteBackend,
  GraphLifecycleBackend,
  GraphReadBackend,
  HardDeleteEdgeParams,
  HardDeleteNodeParams,
  HardDeleteUniquesByConcreteKindParams,
  HardDeleteUniquesByNodeIdsParams,
  HybridSearchParams,
  HybridSearchRow,
  IdentityTableNames,
  IndexMaterializationBackend,
  IndexMaterializationRow,
  InsertEdgeParams,
  InsertNodeParams,
  InsertSchemaParams,
  InsertUniqueParams,
  KindRemovalRow,
  LiveNodeRow,
  LockSchemaVersionForWriteParams,
  NodeEntityReadBackend,
  NodeEntityWriteBackend,
  NodeFulltextSync,
  NodeInsertClaim,
  NodeInsertClaimVerdict,
  NodeInsertMode,
  NodeCreatePlan,
  NodeInsertProjection,
  NodeRow,
  PessimisticLockCapabilities,
  PopulatedSchemaKind,
  PurgeEdgeClaimsParams,
  QueryExecutionBackend,
  RawQueryExecutionBackend,
  RawStatementExecutionBackend,
  ReadConstraintFenceViolationsParams,
  RecordContributionMaterializationParams,
  RecordedRelationDdl,
  RecordedTableNames,
  RecordIndexMaterializationParams,
  RecordKindRemovalParams,
  RecursiveTraversalCapability,
  ReleaseIndexMaterializationClaimParams,
  RemovalMaterializationBackend,
  RowProps,
  SchemaCommitBackend,
  SchemaCommitPreflightBackend,
  SchemaKindEmptinessProbe,
  SchemaReadBackend,
  SchemaVersionRow,
  SchemaWriteFenceBackend,
  SetActiveVersionParams,
  SqlCompilationBackend,
  TombstonedNodeRow,
  TransactionBackend,
  TransactionOptions,
  TransactionReadBackend,
  TrustedImportOptions,
  TrustedImportSession,
  UniqueConstraintBackend,
  UniqueRow,
  UpdateEdgeParams,
  UpdateNodeParams,
  UpdateNodeSetParams,
  UpdateNodeSetResult,
  UpsertEmbeddingBatchParams,
  UpsertEmbeddingBatchRow,
  UpsertEmbeddingParams,
  UpsertFulltextBatchParams,
  UpsertFulltextParams,
  VectorCapabilities,
  VectorIndexType,
  VectorMetric,
  VectorOperationBackend,
  VectorSearchFrontierTuning,
  VectorSearchParams,
  VectorSearchResult,
} from "./types";
export {
  D1_MAX_BIND_PARAMETERS,
  DATABASE_EXTENSION_NAMES,
  DURABLE_OBJECT_MAX_BIND_PARAMETERS,
  isLiveNodeRow,
  isTombstonedNodeRow,
  MODERN_SQLITE_MAX_BIND_PARAMETERS,
  normalizeGraphAnalyticsCapabilities,
  POSTGRES_CAPABILITIES,
  POSTGRES_MAX_BIND_PARAMETERS,
  rowPropsToJsonText,
  rowPropsToObject,
  SQLITE_CAPABILITIES,
  SQLITE_MAX_BIND_PARAMETERS,
} from "./types";

// Supporting vocabulary referenced by the authoring contracts above. Keeping
// it nameable from this entrypoint makes API Extractor's forgotten-export
// diagnostic a zero-tolerance gate for future backend contract additions.
export type { GraphIdentityConfig } from "../core/define-graph";
export type { RecordedInstant } from "../core/temporal";
export type {
  Cardinality,
  Collation,
  DeleteBehavior,
  EndpointExistence,
  IndexEntity,
  JsonValue,
  KindAnnotations,
  KindEntity,
  NullCheckOp,
  TemporalMode,
  UniquenessScope,
} from "../core/types";
export type {
  ExtensionArrayItemType,
  ExtensionArrayProperty,
  ExtensionBooleanProperty,
  ExtensionEdgeDef,
  ExtensionEdgeIndex,
  ExtensionEmbeddingModifier,
  ExtensionEnumProperty,
  ExtensionIndex,
  ExtensionIndexWhere,
  ExtensionNodeDef,
  ExtensionNodeIndex,
  ExtensionNumberProperty,
  ExtensionObjectFieldProperty,
  ExtensionObjectProperty,
  ExtensionOntologyRelation,
  ExtensionPropertyModifiers,
  ExtensionPropertyType,
  ExtensionSearchableModifier,
  ExtensionStringProperty,
  ExtensionUniqueConstraint,
  ExtensionUniqueWhere,
  GraphExtension,
  GraphExtensionVersion,
} from "../graph-extension/extension-types";
export type {
  EdgeIndexDeclaration,
  EdgeIndexDirection,
  IndexDeclaration,
  IndexDeclarationBase,
  IndexOrigin,
  IndexScope,
  IndexWhereExpression,
  IndexWhereLiteral,
  IndexWhereOp,
  IndexWhereOperand,
  NodeIndexDeclaration,
  RelationalIndexDeclaration,
  RelationalIndexMethod,
  SystemColumnName,
  VectorIndexDeclaration,
  VectorIndexImplementation,
  VectorIndexMetric,
  VectorIndexParams,
} from "../indexes/types";
export type { MetaEdgeName } from "../ontology/constants";
export { ALL_META_EDGE_NAMES } from "../ontology/constants";
export type { InferenceType } from "../ontology/types";
export type { ValueType } from "../query/ast";
export type { JsonPointer } from "../query/json-pointer";
export type {
  JsonSchema,
  SerializedClosures,
  SerializedEdgeDef,
  SerializedMetaEdge,
  SerializedNodeDef,
  SerializedOntology,
  SerializedOntologyRelation,
  SerializedSchema,
  SerializedUniqueConstraint,
} from "../schema/types";
