name: Bug Report
description: Create a report to help us improve
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction
      description: |
        Please provide a code sample or a link to a minimal reproduction. 
        You can use our examples as a starting point.
      placeholder: |
        ```typescript
        // Paste your code here
        ```
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: TypeGraph Version
      description: Which version of typegraph are you using?
      placeholder: 0.1.0
  - type: dropdown
    id: database
    attributes:
      label: Database Backend
      options:
        - SQLite
        - PostgreSQL
        - Other
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
