name: Feature Request
description: Suggest an idea for this project
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature!
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What is the problem you are trying to solve?
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Suggested Solution
      description: Describe the solution you'd like.
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Describe alternatives you've considered.
